language: node_js
node_js:
- '10'
sudo: required
services:
- docker
- mongodb
script:
- npm run test
deploy:
  provider: gae
  project: order-ms-259919
  keyfile: gce.json
  skip_cleanup: true
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_1d99e27a155f_key -iv $encrypted_1d99e27a155f_iv
  -in gce.json.enc -out gce.json -d
